FROM keinos/php8-jit:latest

ADD entrypoint.sh /entrypoint.sh

USER root

RUN apk add --no-cache bash gmp gmp-dev && \
    docker-php-source extract && \
    docker-php-ext-install gmp && \
    ln -s /usr/local/bin/php /usr/bin/php && \
    chmod +x /entrypoint.sh && \
    chown -R nobody:nobody /entrypoint.sh

USER nobody

CMD /entrypoint.sh
VOLUME /code
